# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49c41d5cb0d0a2eddb17d5370927183a2f15997a1a71fd4a2cb7559147fe3bc7d716c91283258c63a60b7edc1306bc4e5d592104fc9127a56df316fab349d51b

test:
  secret_key_base: 3871397e2bdc7da16a632f29e83a0a3eb60b7d1c51ea1ac1e5dffb94e0446ee000f4ed290526e3f4a1fe0b151b6ba6b877059dc448793a10a922c0143c02fc72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
